version: 2

models:
  - name: purchases
    config:
      event_time: date
  - name: abc
    description: bla bla
    meta:
      joins:
        - join: foo
        - join: incremental

  - name: public_model
    access: public

  - name: for_katie
    description: "running some auto exposure tests."