version: 2

models:
  - name: abc
    description: bla bla
    meta:
      joins:
        - join: foo
        - join: incremental
  - name: foo
    access: public
    description: testing stuff
    data_tests:
      - some_test:
        name: some_test
        severity: warn

  - name: incremental
    config:
      materialized: incremental
      incremental_strategy: merge

  - name: public_model
    access: public