version: 2

models:
  - name: purchases
    config:
      event_time: date
  - name: abc
    description: bla bla
    meta:
      joins:
        - join: foo
        - join: incremental
  - name: foo
    access: public
    description: testing stuff

  - name: incremental
    config:
      materialized: incremental
      incremental_strategy: merge

  - name: public_model
    access: public