version: 2

sources:
  - name: jaffle_shop
    database: analytics
    tables:
      - name: abc
        columns:
          - name: id
      - name: orders
        columns:
          - name: id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
          - name: status
            description: Note that the status can change over time

      - name: customers

  - name: stripe
    tables:
      - name: payments
